- main.py
Apply hotfixes to the sip dependency for pyqt 5.9.2 and the nccl dependecy of pytorch
> Hotfix pyqt 5.9.2 and pytorch

- main.py
replace dependecies on "openssl >=1.1.1,<1.2.0a0" with
"openssl >=1.1.1a,<1.1.2a" as openssl uses non-PEP440 version numbers.
> openssl 1.1.1 dependency fix

- main.py
Remove the qt-5.9.7-h468cd18_0.tar.bz2 package from the osx-64 index.
This package contains dylibs with .conda. added to the name which are
incompatible with earlier qt 5.9 releases and downstream packages.
> remove qt-5.9.7-h468cd18_0 from index

- r.py
- test-hotfix.py
test tool shows you a diff of what your current changes do.
```
python test-hotfix.py r --subdir=linux-64
```
Note that it's a diff from whatever the remote is.  If the remote has the same patches applied that you have locally, it should show nothing.  It should only show changes that you have relative to what is deployed.
> fix unpinned mro-base dep; add test tool

- main.py
Use the _tflow_select dependency to select the appropiate tensorflow variant
for all versions of tensorflow and the variant metapackages.
Previously tensorflow 1.8.0, 1.9.0 and 1.10.0 uses the _tflow_180_select,
_tflow_190_select and _tflow_1110_select packages for selection.
> tensorflow _tflow_select substitutions

- main.py
Package built with cudnn 7.x.y are compatible at run time with
cudnn>=7.x.y,<8.0a0 (technically >=7.x.0,8.0a0).  Adjust existing over and
under pinned packages with the correct versions.
> fix cudnn version depends

- main.py
These packages have an incorrect build number and dependencies.
> remove libtiff build 1001 files from repository

- r.py
This switches the default R implementation from MRO to anaconda R for new envs.  Old envs created with MRO will need to be migrated.  Tool for that created at https://github.com/ContinuumIO/mro-migrator
> flip mutex track_feature to make anaconda the default R

- main.py
```
(base) ➜  ~ conda search \
--info \
'libssh2[subdir=osx-64,version=1.8.0,build=h1218725_2]' \
| grep dependencies
dependencies: []
```
> revoke bad build of libssh2 (osx-64)

- main.py
Set the build_number of the linux-ppc64le::main::blas-1.0-openblas.tar.bz2
package to 7 to match the package in free.
Provides a temporary solution to the know case of conda/conda#8302
> set blas pkg build_num to 7 for linux-ppc64le main

- main.py
Add constrains entry to the numpy-base packages in pkgs/main.  Without this
environment can be created with mixed version of numpy and numpy base.  For
example:
conda create -n example numpy=1.13 numpy-base=1.16
> add run constrains to numpy-base packages

- main.py
Change the ipykernel version bounds for the sparkmagic packages from
>=4.2.2 to >=4.2.2,<4.10.0
see AnacondaRecipes/sparkmagic-feedstock#3
> fix ipykernel dependency for sparkmagic

- main.py
https://github.com/conda/conda/issues/8844#issuecomment-506992734
> Add dep on libgcc mutex package

- index_versions.yml
This goes with conda-build's current_repodata.json.  Any entries here are ensured to stay in the trimmed repodata.  The newest version is implicit and does not need to be supplied.
> add index_versions.yml file for indexing additional current repodata

- main.py
This is causing problems for me:
```
PackagesNotFoundError: The following packages are not available from current channels:
- pkgs/main/linux-64::tensorflow==1.8.0=h7b2774c_0 -> _tflow_select==1.2.0=eigen
```
See also https://github.com/conda/conda/issues/8863#issuecomment-510394224
> main.py: fix typo in TFLOW_SUBS

- main.py
De-prioritize libarchive packages which lack support for zstd.  Zstd is
used by .conda packages and therefore requires libarchive to include
support for reading this files.  Rather than remove the packages which
lack this support add a track_feature via the _low_priority package to
make these packages less appealing to the solver.
> de-prioritize libarchive packages which lack zstd

- main.py
this build has missing dependencies and is causing people problems.  Build 1 or newer should be preferred in all cases.
> revoke libarchive 3.3.3 build 0

- main.py
Update all pre-build 17 packages to match the dependency of that build.
cf: https://github.com/AnacondaRecipes/aggregate/pull/164
> hotfix clang_osx-64 packages to correct depends

- main.py
glib is ABI compatible to the major version, adjust existing dependency
information to loosen requirements which require major.minor bounds.
> loosen glib upper bound

- main.py
I checked the current repodata that all cases where setuptools appear in constains it is "setuptools >=31.0.1"
> remove setuptools from conda's constrains

- main.py
Loosen the binutils_impl_ dependency in gcc_impl_ packages from an exact
pinning to be >= version,<3.
> loosen binutils_impl_ dependency in gcc_impl_

- main.py
Hotfix numba version 0.46.0 and 0.47.0 to include a run requirement on
setuptools.
> hotfix numba to include setuptools requirement

- main.py
Correct the sip run requirement for three pyqt packages which were built
against sip 4.19.13.
> correct sip req for pyqt pkgs build w/ sip 4.19.13

- main.py
expand the compatibility of mkl 2019 to include 2020
depends entries of "mkl >=2019.x,<2020.0a0" to
"mkl >=2019.x,<2021.0a0"
> expand mkl 2019 bound to 2020

- main.py
Do not expand the version bounds for packages build with mkl 2019 to
include mkl 2020 on osx-64 as older version of macOS (e.g. 10.10) are
not able to find the necessary libraries.
Undo bound expansion in packages that were earlier expanded.
> do not expand mkl 2019 bounds on osx-64

- main.py
spyder 4.0.0 and 4.0.1 should include a lower bound on psutil of 5.2 and
should pin parso to 0.5.2.
see:
https://github.com/conda-forge/spyder-feedstock/pull/73
https://github.com/conda-forge/spyder-feedstock/pull/74
> adjust depends for spyder 4.0.0 and 4.0.1

- main.py
kealib change sonames in the 1.4.8 release making in incompatible with
earlier releases. Adjust the dependency information for packages to
account for this incompatibility.
> adjust kealib depends to account for soname change

- main.py
Change the upper bound on the spyder-kernels requirement for the
spyder 4.0.0 and 4.0.1 packages to 1.9.0 from 2.0.0
> change upper bound on spyder-kernel req to 1.9.0

- main.py
This reverts commit b7f3c088fa92e6c7e25b414b6d8ada9ab1b959a0.
Hotfixing not applied to the free channel which has caused some breakage for users on older versions of conda. We need to temporarily revert this until we have a plan for applying this to the free channel
> Revert "Add a constraint on python_abi"

- main.py
libffi broke ABI with the 3.3 release:
https://abi-laboratory.pro/index.php?view=objects_report&l=libffi&v1=3.2.1&v2=3.3
Adjust the bounds for packages which depend on libffi to have an upper
bound of <3.3a0.
> hotfix libffi to account for 3.3 ABI breakage

- main.py
Fixes https://github.com/conda/conda/issues/9115
Adds `run_constrained` to `cudatoolkit` to require a minimum `__cuda` version. This should ensure that when `__cuda` is present on a system; we use that to determine whether a particular version of `cudatoolkit` (and packages that depend on that version) can or cannot be installed.
cc @jjhelmus
> Add `run_constrained` with `__cuda` to `cudatoolkit`

- main.py
The ZeroMQ Windows DLL name includes the patch number, so we need to tighten the constraint for win-* packages that depend on ZeroMQ. If we don't, our next ZeroMQ update (for Anaconda 2020.06) will blow up existing environments.
> Further constrain ZeroMQ upper bound on Windows

- main.py
Fix the depends info for pytest-openfiles 0.5.0 and pytest-doctestsplus
0.7.0.
See https://github.com/ContinuumIO/anaconda-issues/issues/11864
> fix pytest-openfiles and pytest-doctestplus deps

- main.py
* Add a constrains to the intel-openmp 2020.2 packages to require mkl >=2020.2
* Generalize constrains so that they apply to future versions.
> constrain intel-openmp 2020.2 and future versions

- main.py
Removing this prevents unexpected downgrades when running with newer Python build; instead, trusting the associated Python package to properly restrict the libffi version.
> Exclude "_anaconda_depends" from libffi hotfixes

- main.py
Tested with `test-hotfix.py` for all platforms including linux-s390x. Only changes was the addition of numpy for linux-s390x.
There is an error during `conda-index` that causes the command to fail, not updating the index for this platform.
> Adding linux-s390x subdir to support numpy.

- main.py
Reflects upstream changes to minimum numpy version required. Fixes ContinuumIO/anaconda-issues#12269
> Fix numpy version required by astropy 4.2

- main.py
Version 4.2.4 was not released on Conda-Forge and these updates were missed in our release. The requirements were included in the PR for 4.2.5.
Reference PR on Conda-Forge recipe: [https://github.com/conda-forge/spyder-feedstock/pull/102/files](https://github.com/conda-forge/spyder-feedstock/pull/102/files)
> Hotfixes for Spyder v4.2.4

- main.py
Fixes AnacondaRecipes/repodata-hotfixes#103.
diff output from `python test-hotfix.py main --subdir noarch`:
```
--- main/noarch/reference_repodata.json	2021-04-02 13:34:38.691185038 -0500
+++ main/noarch/repodata-patched.json	2021-04-02 13:38:28.023150358 -0500
@@ -14560,26 +14560,22 @@
"dask-2021.3.1-pyhd3eb1b0_0.tar.bz2": {
"build": "pyhd3eb1b0_0",
"constrains": [
"openssl !=1.1.1e"
],
"depends": [
"bokeh >=1.0.0,!=2.0.0",
-        "cloudpickle >=0.2.2",
"cytoolz >=0.8.2",
"dask-core 2021.3.1.*",
"distributed >=2021.3.1",
-        "fsspec >=0.6.0",
"numpy >=1.15.1",
"pandas >=0.25.0",
-        "partd >=0.3.10",
-        "python >=3.6",
-        "toolz >=0.8.2"
+        "python >=3.7"
],
"license": "BSD-3-Clause",
"md5": "630e2511f4639702428de14ed89cbe45",
"name": …
```
> Fix dependencies for dask-core, dask 2021.3.1

- main.py
Changes for this hot fix:
```
--- main/noarch/reference_repodata.json	2021-04-02 15:26:32.927886021 -0500
+++ main/noarch/repodata-patched.json	2021-04-02 15:26:39.187777022 -0500
@@ -14624,7 +14624,7 @@
"cytoolz >=0.8.2",
"dask-core 2021.3.1.*",
"distributed >=2021.3.1",
-        "numpy >=1.15.1",
+        "numpy >=1.16",
"pandas >=0.25.0",
"python >=3.7"
],
@@ -77138,7 +77138,7 @@
"cytoolz >=0.8.2",
"dask-core 2021.3.1.*",
"distributed >=2021.3.1",
-        "numpy >=1.15.1",
+        "numpy >=1.16",
"pandas >=0.25.0",
"python >=3.7"
],
```
> Correct numpy dependency for dask 2021.03.1

- main.py
Space between operator and version was causing conda to fail with `Invalid spec: >=`.  Fixes AnacondaRecipes/dask-core-feedstock#3.
Resulting repodata.json diff:
```
--- a/main/noarch/reference_repodata.json
+++ b/main/noarch/repodata-patched.json
@@ -15743,7 +15743,7 @@
"python >=3.7",
"cloudpickle >=1.1.1",
"fsspec >=0.6.0",
-        "partd >= 0.3.10",
+        "partd >=0.3.10",
"pyyaml",
"toolz >=0.8.2"
],
@@ -79198,7 +79198,7 @@
"python >=3.7",
"cloudpickle >=1.1.1",
"fsspec >=0.6.0",
-        "partd >= 0.3.10",
+        "partd >=0.3.10",
"pyyaml",
"toolz >=0.8.2"
],
```
> Fix error in dask dependency specification

- main.py
Repodata diff:
```
--- main/noarch/reference_repodata.json	2021-05-14 12:55:52.677460048 -0500
+++ main/noarch/repodata-patched.json	2021-05-14 12:56:05.221417236 -0500
@@ -24184,12 +24184,12 @@
"gitpython-3.1.17-pyhd3eb1b0_1.tar.bz2": {
"build": "pyhd3eb1b0_1",
"build_number": 1,
"depends": [
"gitdb >=4.0.1,<5",
-        "python >=3.4",
-        "smmap >=3.0.1,<4"
+        "python >=3.5",
+        "typing-extensions >=3.7.4.0"
],
"license": "BSD-3-Clause",
"license_family": "BSD",
"md5": "c57ad4b1450291c4db46dc08093ba138",
"name": "gitpython",
@@ -89699,12 +89699,12 @@
"gitpython-3.1.17-pyhd3eb1b0_1.conda": {
"build": "pyhd3eb1b0_1",
"build_number": 1,
"depends": [
"gitdb >=4.0.1,<5",
-        "python >=3.4",
-        "smmap >=3.0.1,<4"
+        "python >=3.5",
+ …
```
> Fix gitpython 3.1.17 dependencies

- main.py
Added patch to get click dependency version <8.0 for the package click-repl in main.py
> Added patch to get click dependency version <8.0 for click-repl

- main.py
See code comments for details; basically, extend the patch we already apply for zstd 1.4.4 to all of the zstd 1.4.x releases.
References: https://abi-laboratory.pro/index.php?view=timeline&l=zstd
Used `nm` + `grep` to check, and none of our linux-64 packages that depend on `zstd >=1.4.x` require the `ZSTD_getSequences` symbol [removed in zstd 1.4.7](https://abi-laboratory.pro/index.php?view=objects_report&l=zstd&v1=1.4.5&v2=1.4.7). Assuming the same applies for the other platforms.
Partial repodata.json diff:
```
--- main/linux-64/reference_repodata.json	2021-05-28 19:36:59.000000000 -0500
+++ main/linux-64/repodata-patched.json	2021-05-28 20:41:45.000000000 -0500
@@ -42070,15 +42070,15 @@
"orc >=1.6.5,<1.6.6.0a0",
"python >=3.6,<3.7.0a0",
"re2",
"snappy >=1.1.8,<2.0a0",
"uriparser", …
```
> Loosen zstd 1.4.x requirements

- main.py
Almost miraculously, HDF5 has remained ABI compatible between 1.10.4 to 1.10.7, inclusive (https://abi-laboratory.pro/index.php?view=timeline&l=hdf5). Update "depends" metadata for packages using those HDF5 versions to save ourselves a lot of rebuilding pain.
Partial diff from applying this patch:
```
--- main/linux-64/repodata-reference.json
+++ main/linux-64/repodata-patched.json
@@ -167340,19 +167340,19 @@
"size": 1107971,
"subdir": "linux-64",
"timestamp": 1534896366448,
"version": "2.8.0"
},
"h5py-2.9.0-py27h7918eee_0.tar.bz2": {
"build": "py27h7918eee_0",
"depends": [
-        "hdf5 >=1.10.4,<1.10.5.0a0",
+        "hdf5 >=1.10.4,<1.10.8.0a0",
"libgcc-ng >=7.3.0",
"numpy >=1.11.3,<2.0a0",
"python >=2.7,<2.8.0a0",
"six",
"unittest2"
],
"license": "BSD-3-Clause", …
```
> Relax bounds on HDF5 1.10.x requirements

- main.py
Reverts AnacondaRecipes/repodata-hotfixes#121.
Users reporting issues like this:
```
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning …
```
> Revert "Relax bounds on HDF5 1.10.x requirements"

- main.py
I've prepared fixes for **distributed 2021.5.0** and **distributed 2021.4.1**.
There was a wrong dependency inside meta.yaml files
Compare how it was fixed for the next and last version of distributed **2021.5.1** https://github.com/AnacondaRecipes/distributed-feedstock/blob/master/recipe/meta.yaml
> Fix distributed 2021.5.0

- main.py
Added patch for aiobotocore v1.2.* to get botocore v1.19.52
Issue:
https://github.com/AnacondaRecipes/repodata-hotfixes/issues/125
> Added patch for aiobotocore v1.2.* to get botocore v1.19.52

- main.py
Need to fix our recipe so this doesn't happen again. Output of `test-hotfix.py`:
```
--- main/noarch/repodata-reference.json
+++ main/noarch/repodata-patched.json
@@ -26912,11 +26912,12 @@
"gitpython-3.1.18-pyhd3eb1b0_0.tar.bz2": {
"build": "pyhd3eb1b0_0",
"depends": [
"gitdb >=4.0.1,<5",
-        "python >=3.5"
+        "python >=3.5",
+        "typing-extensions >=3.7.4.0"
],
"license": "BSD-3-Clause",
"license_family": "BSD",
"md5": "f835aeea5611ba5125dd0b0a378176a6",
"name": "gitpython",
@@ -100627,11 +100628,12 @@
"gitpython-3.1.18-pyhd3eb1b0_0.conda": {
"build": "pyhd3eb1b0_0",
"depends": [
"gitdb >=4.0.1,<5",
-        "python >=3.5"
+        "python >=3.5",
+        "typing-extensions >=3.7.4.0"
],
"license": "BSD-3-Clause",
"license_family": …
```
> Add typing-extensions dependency to gitpython=3.1.18

- main.py
Newer versions of GCC runtime libraries (`lib*-ng`) were built using CentOS 7 as a target; adding the `__glibc` depends prevents the conda solver from considering these newer releases on older systems (e.g., CentOS 6) and breaking conda environments. Adding these depends to the GCC runtime libraries has the added benefit of basically eliminating the need to add similar constraints to packages built using newer compilers.
Fixes AnacondaRecipes/repodata-hotfixes#126
Proposed repodata.json changes:
```
--- main/linux-64/repodata-reference.json	2021-07-01 10:56:07.350589280 -0500
+++ main/linux-64/repodata-patched.json	2021-07-01 10:57:08.768270856 -0500
@@ -208207,15 +208207,16 @@
"build_number": 17,
"constrains": [
"libgomp 7.5.0 h5101ec6_17"
],
"depends": [
"_libgcc_mutex 0.1 main", …
```
> Add `__glibc` depends to newer GCC runtime libraries

- .flake8
- .github/flake8-matcher.json
- .github/workflows/ci.yml
Linting findings do not block CI, but they are visualised via problem matcher in the PR diff.
> Add lint step with flake8 and problem matcher to github action

- r.py
Ensure that r package metadata has 'subdir' fields by updating the hotfixes specified in r.py to check.
Please note that like many of the patching instructions, this does not change repodata about .conda packages (which is kept in the "packages.conda" dict in repodata.)
This tested successfully on a local repository and then on the actual build network.
In the future, a cleaner structure around required fields would be beneficial.
> Ensure that r package metadata has 'subdir' fields

- main.py
Loosen `dask-core` requirement to match upstream specifications; this also resolves a dependency conflict that prevented the `anaconda=2021.05` meta-package from being installed.
> Fix depends for distributed=2021.4.1

- main.py
Some builds of our `openblas` package incorrectly list a non-existent build of the `nomkl` package as a dependency.
Fixes AnacondaRecipes/repodata-hotfixes#114; fixes ContinuumIO/anaconda-issues#12342.
> Fix `nomkl` build string used as OpenBLAS dependency

- main.py
`pyjwt` 2.1.0 packages for Python <3.9 have incorrectly specified run dependencies on `cryptography`; this repodata patch addresses that issue. Note that the feedstock seems to be correct.
Partial diff of this patch (linux-64 shown here, but similar results for all platforms):
```
--- main/linux-64/repodata-reference.json
+++ main/linux-64/repodata-patched.json
@@ -327375,12 +327375,14 @@
"version": "2.0.1"
},
"pyjwt-2.1.0-py36h06a4308_0.tar.bz2": {
"build": "py36h06a4308_0",
+      "constrains": [
+        "cryptography >=3.3.1,<4.0.0"
+      ],
"depends": [
-        "cryptography >=2.6,<3.0.0",
"python >=3.6,<3.7.0a0"
],
"license": "MIT",
"license_family": "MIT",
"md5": "b0551c9f70d9de0ef12f89df8bce0258",
@@ -327392,12 +327394,14 @@
"version": "2.1.0"
}, …
```
> Fix `cryptography` depends/contraints for pyjwt=2.1.0

- main.py
1.Updated numpy version from >=1.17 to >=1.20.2,<2.0a0. for pyerfa 2.0.0
This is a fix for https://github.com/AnacondaRecipes/repodata-hotfixes/issues/123
> Updated numpy version for pyerfa 2.0.0

- main.py
Our updated recipe used a run constrains to enforce a minimum version of Python 3.7; however, due to a bug(?) and/or non-intuitive behavior in the conda solver, having a run constrain seems to completely override any version requirements specified in the `depends` section for the corresponding package. This repodata patch removes the run constrains and just patches the minimum version for the Py3.7 build.
Fixes pandas-dev/pandas#42627
Partial result from this patch:
```
--- main/linux-64/repodata-reference.json
+++ main/linux-64/repodata-patched.json
@@ -285716,20 +285716,18 @@
"version": "1.2.5"
},
"pandas-1.3.0-py37h295c915_0.tar.bz2": {
"build": "py37h295c915_0",
-      "constrains": [
-        "python !=3.7.0"
-      ],
+      "constrains": [],
"depends": [ …
```
> pandas 1.3.0: remove run constrains; fix Py3.7 depends spec

- main.py
Resulting changes:
```
--- main/linux-64/reference_repodata.json	2021-07-28 14:55:03.000000000 -0500
+++ main/linux-64/repodata-patched.json	2021-07-28 14:55:30.000000000 -0500
@@ -77954,25 +77954,6 @@
"timestamp": 1625814764180,
"version": "1.14.6"
},
-    "cffi-1.14.6-py36h7f8727e_0.tar.bz2": {
-      "build": "py36h7f8727e_0",
-      "build_number": 0,
-      "depends": [
-        "libffi >=3.2.1,<3.3a0",
-        "libgcc-ng >=7.5.0",
-        "pycparser >=2.06",
-        "python >=3.6,<3.7.0a0"
-      ],
-      "license": "MIT",
-      "license_family": "MIT",
-      "md5": "f868026cac8288e56fa44bb08615f1de",
-      "name": "cffi",
-      "sha256": "a7a7186e027822416d33606ed44673161783b36e0788b2e458d6a47453752040",
-      "size": 228871,
-      "subdir": "linux-64",
- …
```
> "Remove" cffi 1.14.6 packages with broken run depends

- main.py
Needed to successfully install openblas=0.3.13 across all platforms; impacted packages:
```
linux-64/openblas-devel-0.3.13-h06a4308_0.conda {'nomkl 3.0 h06a4308_0'} => {'nomkl 3.0 0'}
linux-64/openblas-devel-0.3.13-h06a4308_0.tar.bz2 {'nomkl 3.0 h06a4308_0'} => {'nomkl 3.0 0'}
linux-aarch64/openblas-devel-0.3.10-hd43f75c_1.conda {'nomkl 3.0 hd43f75c_0'} => {'nomkl 3.0 0'}
linux-aarch64/openblas-devel-0.3.10-hd43f75c_1.tar.bz2 {'nomkl 3.0 hd43f75c_0'} => {'nomkl 3.0 0'}
linux-aarch64/openblas-devel-0.3.13-hd43f75c_1.conda {'nomkl 3.0 hd43f75c_0'} => {'nomkl 3.0 0'}
linux-aarch64/openblas-devel-0.3.13-hd43f75c_1.tar.bz2 {'nomkl 3.0 hd43f75c_0'} => {'nomkl 3.0 0'}
linux-ppc64le/openblas-devel-0.3.13-h6ffa863_0.conda {'nomkl 3.0 h6ffa863_0'} => {'nomkl 3.0 0'} …
```
> Update `nomkl` requirements for openblas-devel 0.3.13

- main.py
This is breaking `matplotlib` (AnacondaRecipes/freetype-feedstock#3),
and it's quite possible, even likely, that this version/build will break
other things.  Yank freetype until we figure out what's going on.
> Yank freetype 2.11.0 for Windows

- main.py
`click-repl` 0.2.0 fixed its compatibility issue with newer `click` releases.
> Unpin click dependency for click-repl >=0.2

- main.py
I discovered that our build of `click 8.0.0` does not bound Python properly. It dropped support for Python <3.6 with 8.0. This is breaking an AE5 use case
> click 8: needs a python >=3.6 bound

- main.py
We have been building packages against `numpy 1.21.5` on linux-aarch64, when we should have been building against an earlier version of NumPy for maximum forward compatibility. It looks like the reason for this is that the numpy version specificed in conda-build-config.yaml is ignored if a recipe uses an explicit version bound.
Those recipe issues need to be fixed, but in the meanwhile, here is a patch that relaxes a bound of 1.21.5 to 1.21.2. This is obviously not going to negatively impact anyone running 1.21.5 on linux-aarch64, but we have one partner use case where they are aligning on 1.21.2 between linux-64 and linux-aarch64. This patch allows the affected packages to be successfully be used in this case.
cc: @chenghlee
> Re-pin linux-aarch numpy 1.21.5 packages

- main.py
Avoid breaking API changes in libmambapy 0.23; fix #157.
X-ref: conda-forge/conda-forge-repodata-patches-feedstock#251
> Re-pin conda-libmamba-solver's libmambapy dependency

- main.py
conda 4.13.0 removed older code that break conda-build <=3.21.8; see conda/conda-build#4481.
> Set upper bounds for conda with older conda-build releases

- main.py
snowflake-snowpark-python needs to pin cloudpickle to 2.0.0 or less (yes, <=) according to the upstream authors. Version 0.7.0 already has the correct pin; only 0.6.0 is affected.
```
***************
*** 552125,552135 ****
"constrains": [
"pandas >1,<1.4"
],
"depends": [
!         "cloudpickle >=1.6.0",
"python >=3.8,<3.9.0a0",
"snowflake-connector-python",
"typing-extensions >=4.1.0"
],
"license": "Apache-2.0",
--- 552125,552135 ----
"constrains": [
"pandas >1,<1.4"
],
"depends": [
!         "cloudpickle >=1.6.0,<=2.0.0",
"python >=3.8,<3.9.0a0",
"snowflake-connector-python",
"typing-extensions >=4.1.0"
],
"license": "Apache-2.0",
```
> upper bound for cloudpickle for snowflake-snowpark-python

- main.py
This relaxes the tensorflow-base-2.8.2 scipy deps from `scipy >=1.7.3` to `scipy >=1.7.1`. This is to ensure that we can create environments for linux-64 and linux-aarch64 with synchronized versions of scipy and tensorflow 2.8. Our team has confidence in compatibility at the binary level for this relaxation.
> slight relaxation of scipy for linux-64 tensorflow-base 2.8.2

- main.py
Keeps the `numpy` lower bounds set in the [aggregate/conda_build_config.yaml](url) but changes the upper bound to be the one specified upstream (`<1.23`): https://github.com/scipy/scipy/blob/v1.7.3/setup.py#L551-L552
Addresses this warning (which was causing failures for the Numba team):
```
UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
```
> Set upper bound on scipy-1.7.3 (build 0) according to upstream reqs

- main.py
numba has numpy requirements enforced through imports checks.
For 0.55.1 and above the bounds are set correctly
For 0.53.1 and below numba doesn't set upper bounds.
0.54.1 and 0.55.0 are not set properly.
This PR adds a run constraint to match numba code:
https://github.com/numba/numba/blob/0.54.1/numba/__init__.py#L135
https://github.com/numba/numba/blob/0.55.0/numba/__init__.py#L137
> add numpy constraints for numba 0.54.1 and 0.55.0

- main.py
Numba has numpy constraints that were not handled in conda packages 0.54.0 0.54.1 and 0.55.0.
The numpy constraint added via hotfix in PR #170 and #171 are too strict and break installation of anaconda 2021.11. (See #172).
This change corrects the constraints.
See:
https://github.com/numba/numba/blob/0.54.1/numba/__init__.py#L137
https://github.com/numba/numba/blob/0.54.1/numba/np/numpy_support.py#L15
https://github.com/numba/numba/blob/0.55.0/numba/__init__.py#L139
https://github.com/numba/numba/blob/0.55.0/numba/np/numpy_support.py#L16
> adjusting numpy upperbound for numba 0.54 0.55

- main.py
Update conda-libmamba-solver version; avoid duplicate conda-libmamba-solver constrains if new 22.11.x build has it.
We decided to release a new build number with updated metadata instead of relying completely on hotfixes, so the improved hotfix should avoid a (harmless) duplicate constraint.
> second fix for conda-libmamba-solver constrains

- main.py
Comes from https://github.com/conda/conda-libmamba-solver/issues/113.
Prevent breakage by an API change.
> pin conda <23.1 in conda-libmamba-solver

- main.py
With conda's tests depending on flask and jinja2 through conda-build, and jinja2 3.0.1 / 3.0.2 which may fix the issue being rather old by now, drop this problematic constraint.
https://metayaml-conda.fly.dev/metayaml/newest_by_platform?name=jinja2
Should we express a "this jinja2 version is not allowed" dependency?
> Recent jinja2 are no longer a problem for conda-build

- main.py
Comes from https://github.com/conda/conda-libmamba-solver/issues/132
Without this change, conda-libmamba-solver 23.1.0 (which is compatible with conda 23) is also patched.
> limit effect of conda-libmamba-solver pin

- main.py
Fixes [PKG-1117](https://anaconda.atlassian.net/jira/software/c/projects/PKG/issues/PKG-1117) for existing artifacts.
`flask` dependencies have removed deprecated code, making them incompatible with `flask 1.x`. This hotfix pins these dependencies according to v1.1.4: https://github.com/pallets/flask/blob/1.1.4/setup.py#L55-L60
`flask 1.1.4` will be maintained separately: https://github.com/AnacondaRecipes/flask-feedstock/pull/9
Output of `test-hotfixes.py`: [test-hotfix.log](https://github.com/AnacondaRecipes/repodata-hotfixes/files/10736573/test-hotfix.log)
> Flask hotfixes

- main.py
Following PR #184, older versions of anaconda fail to install:
conda create -n anaconda-2022.05_py39 anaconda==2022.05 python=3.9
LibMambaUnsatisfiableError: Encountered problems while solving:
- package flask-1.1.2-pyhd3eb1b0_0 requires click >=5.1,<8.0, but none of the providers can be installed
It seems we can do away without the added restrictions on click and itsdangerous.
> comment flask click and itsdangerous restrictions

- .github/workflows/ci.yml
- Makefile
- main.py
- tests/__init__.py
- tests/test_replace_dep.py
Fixed issues:
- `anaconda-navigator<2.4.0` doesn't completely support `conda>=23.1.0`
- `anaconda-navigator<2.3.0` doesn't completely support `pyqt>=5.15,<6.0a0`
- `anaconda-navigator` has issues with `conda>=22.11.0,<23.1.0`
- `anaconda-client<1.10.0` is incompatible with python 3.10
> NAV-917: conda constrained for old navigator releases

- main.py
There are two changes in conda that cause breaking changes in conda-libmamba-solver:
- https://github.com/conda/conda-libmamba-solver/issues/153
- https://github.com/conda/conda-libmamba-solver/issues/152
There is a matching PR for this in conda-forge https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/419
> Pinning conda-libmamba-solver to only current conda releases

- main.py
numpy needs at least 1.19.5. This hotfix fixes existing uploads for the initial `scipy` build.
Output of `test-hotfix.py`: [test-hotfix.log](https://github.com/AnacondaRecipes/repodata-hotfixes/files/11032458/test-hotfix.log)
> Pin numpy to at least 1.19.5 for scipy 1.10.0 b0

- main.py
The `license_family` value of `versioneer` was incorrectly set to `None` (should have been `PUBLIC-DOMAIN`.
This introduced additional problems when uploading to anaconda.cloud as the schema does not recognize `"None"` (only `None`/`null`).
* Check `license_family` field when creating patch instructions
* Change versioneer `license_family` to `PUBLIC-DOMAIN` if `None`
Hotfix log: [test-hotfix.log](https://github.com/AnacondaRecipes/repodata-hotfixes/files/11390679/test-hotfix.log)
> Versioneer license_family hotfix

- main.py
`isl` and `cloog` are missing the `subdir` property and cause errors in the logs. This hotfix adds the subdir property to any package that's missing it.
[Test output](https://github.com/AnacondaRecipes/repodata-hotfixes/files/11401336/test-hotfix.log)
> Add hotfix for missing subdir

- main.py
**Changes**
- Full details/context can be found in the code comments
- tl;dr Many `pytest-*` plugins transitively included `py` via `pytest` so when `pytest` took the dependency out in v7.2.0, several plugins broke. There are so many plugins we are just assuming this affects all of them to get a fix out the door for damage control. We know of at least two so far that have this issue.
**Issues Encountered**
- N/A
> Hotfixes `pytest-*` plugins to include `py`

- main.py
- Adding in anything that does not have an upper bound on openssl
- Skipping _anaconda_depends as it is a meta package.
> Changes to lead to OpenSSL 3

- main.py
Fixed issues:
- `anaconda-navigator<2.4.1` does not support `conda>=23.5.0`.
_* both `anaconda-navigator==2.4.1` and `conda==23.5.0` are not yet released at the moment of creating this PR._
> NAV-940: conda constrained for old navigator releases

- main.py
Added `urllib3 < 2.0.0a` constraint to all existing `anaconda-client` releases.
General commentaries:
- `anaconda-client>=1.10.0,<1.12.0` required `urllib3 >=1.26.4` which is updated to add upper bound.
- `anaconda-client<1.10.0` used `urllib3` via `requests`. There was no explicit requirement added to the repodata, but which is now added by this hotfix.
- Explicit `urllib3 <2.0.0a` for old anaconda-client releases is also needed so `conda` won't suggest one of the old `anaconda-client` releases for the environment with `urllib3 >=2.0.0a`.
The change was tested before creating this PR - all `repodata.json` files were updated with expected changes.
> AC-165: urllib3 constrained for existing anaconda-client releases

- main.py
Cryptography 41.0.0 is not available on defaults yet so this is a preemptive hotfix.
Xref https://github.com/conda/conda-content-trust/issues/56
Xref https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/462
> `conda-content-trust` is incompatible with `cryptography=41.0.0`

- main.py
From Martin Durant:
It was suggested I cross-post here:
I need some help editing repodata. Ancient versions of s3fs are being picked up, because downgrading it by many years is a fewer number of releases back that it would be to downgrade botocore a few months (which release at least once per week). The version of s3fs being picked up is the last one not to require aiobotocore and a pin on botocore. Since this release predates py3.9, it is reasonable to set the python version bound on it to < 3.9. So I would like to change:
for s3fs <= 0.4.2 on defaults and conda-forge
to python < 3.9 and whatever lower bound already exists (in practice, the lower bound might not matter, because of dependency on fsspec)
Since pip also has this problem, I might separately yank these versions from <=2020 …
> restrict python max version on old s3fs releases

- main.py
See this PR and linked issues:
https://github.com/jupyter/notebook/pull/6749
> upper bound for pyzmq/jupyter_client for notebook<7

- main.py
Fixes issue where conda would downgrade `conda-content-trust` while upgrading `cryptography`, leading to signature verification-related exceptions at runtime.
> Fix `cryptography` pin for older conda-content-trust releases

- main.py
The latest version of ffmpeg we have built has a bad dependency listed for OpenSSL.  This is a hot fix until we get around to rebuilding it either to the latest OR updating.
> Writing hotfix for bad dependency on ffmpeg.

- main.py
anaconda-ident<0.2 is not compatible with anaconda-anon-usage (any version)
anaconda-anon-usage<0.4 is not compatible with anaconda-ident (any version)
We will soon be releasing a version of anaconda-ident that depends on a version range of anaconda-anon-usage, so it's important that we avoid scenarios where they might be downgraded together.
> prevent cross-installs of anaconda-ident<0.2 and anaconda-anon-usage<0.4

- main.py
Issues fixed in this PR:
- some `anaconda-navigator` features don't work on `conda=23.7.3`
- `anaconda-navigator` may fail due to missing `jaraco.classes` imported from `anaconda-cloud-auth`
> NAV-998: navigator-related dependency conflicts

- main.py
https://github.com/conda/conda-build/issues/5026
> add run-constrains on conda-build to conda 23.9.0

- main.py
[Param 2](https://github.com/holoviz/param) is going to be released in the next few days. Param is a foundational library of the [HoloViz ecosystem](https://holoviz.org) and is going through a major release, it comes with breaking changes that can result in a very bad experience if Param 2 is installed with versions not supporting it, as Param's machinery is exerted on class creation and if it fails leads to errors on import.
This PR aims to patch all the HoloViz packages depending on Param to pin them to `param <2`. Ideally, and if this PR is approved of course, it would be merged before Param 2 is released to make sure that users don't create environments with older and incompatible HoloViz packages and Param 2. The next releases of these packages will pin `param >=2,<3`.
A similar …
> Pin holoviz packages to param<2

- main.py
Removing the hotfix due to it currently adding in CVE-2022-42969 into `pytest` through `py`.
CVE: https://nvd.nist.gov/vuln/detail/CVE-2022-42969
Jira Ticket: https://anaconda.atlassian.net/browse/CVE-566
CVE Curation: https://github.com/anaconda-distribution/cve-curations/pull/129/files
I `grepped` through our `pytest` plugin feedstocks to look for any `py` dependencies. In the following PR's I'm adding `py` in as a dependency instead of using the hotfix.
pytest-benchmark-feedstock: https://github.com/AnacondaRecipes/pytest-benchmark-feedstock/pull/3
pytest-cov-feedstock: https://github.com/AnacondaRecipes/pytest-cov-feedstock/pull/5
pytest-csv-feedstock: https://github.com/AnacondaRecipes/pytest-csv-feedstock/pull/1
pytest-flake8-feedstock: …
> Removing py hotfix for CVE-2022-42969

- main.py
conda-build 3.28.x
- [{ticket_number}](#N/A) 
- [Upstream repository](https://github.com/conda/conda-build)
- [Upstream changelog/diff](#N/A)
- ...
- conda-build 3.28 validates menuinst v2 files if detected in the $PREFIX. To do so it imports `menuinst`'s schema and runs `jsonschema` with it.
- On Unix, the only menuinst available is v2, but on Windows v1 is also around. There's a combination of conda, conda-build and menuinst versions that results in a broken import (`ImportError: cannot import name 'data_path' from 'menuinst.utils'`) because conda-build does not require v2 in its metadata.
> Require menuinst 2 in conda-build

- main.py
Notebook 7.0 has changed the way it does extensions, so the post-install scripts won't work.  And probably the extension even if install worked. This will affect everyone that want to easily find and switch conda environments in JupyterNotebooks with nb_conda.
> restrict nb_conda to notebook<7

- .github/workflows/ci.yml
- Makefile
- gen-current-hotfix-report.py
- main.py
- test-hotfix.py
It was reported that conda 24.3.0 breaks conda-build. This PR adds `<24.3.0` as a constraint to the conda dependency on conda-build > 3.21.8 and <24.3.0.
> Pin conda to less than 24.3.0 on conda-build > 3.21.8 and <24.3.0

- main.py
Scipy 1.12.0 requires a minimum version of numpy being 1.22.4. 
It was built with min 1.22.3. This fixes this issue.
> set min numpy bound for scipy 1.12.0

- main.py
Creating an upper bound where none exists.  This also caps the version to be compatible with the older version of numpy that it is targeting.
> Creating update to fix a numpy instance with no uppperbound

- main.py
Remove `navigator-updater=0.5.0` from `defaults`.
This version is broken (_can not be launched from "Update available" dialog in Anaconda Navigator_).
Should be merged after the `navigator-updater=0.5.1` release.
> NAVI-159: remove broken navigator-updater

- main.py
conda-token
- Needs to be released along with conda-token-0.5.0.
> restrict older conda-token to conda <23.9

- main.py
There are currently four `console_shortcut` feedstocks, two for Anaconda and two for Miniconda. This results in four panels in Anaconda Navigator, two of which are redundant. They will soon be consolidated into another feedstock, which would result in six panels.
This hotfix avoids this by removing the data from the recipe. It additionally fixes the problem with redundant panels and also removes the panels of unsupported platforms that had been built in the past.
This will not affect panels where the old `console_shortcut` package has been installed. They will stay until uninstalled.
Hotfix output: [output.txt](https://github.com/user-attachments/files/15878276/output.txt)
> Remove old shortcuts from navigator

- main.py
This reverts commit 6fe91e893f0a2f996f367913507be151bcb89b38.
Reason: conda-token 0.0.5 not yet published to main.
See #229
> Revert "restrict older conda-token to conda <23.9"

- main.py
This re-establish the change from #229 and will be published at the same time as the updated-conda-token: https://github.com/AnacondaRecipes/conda-token-feedstock/pull/4
> Revert "Revert "restrict older conda-token to conda <23.9""

- main.py
The current integration of menuinst2 is causing issues with installers and uninstallers and thus have to be reverted. This hotfix revokes the currently broken packages so that they don't appear in solvers.
Output of test-hotfixes: [hotfix.log](https://github.com/user-attachments/files/15980426/hotfix.log)
> Revoke menuinst2

- main.py
conda-libmamba-solver (all versions so far)
- ticket_number: N/A
- [Upstream repository](https://github.com/conda/conda-libmamba-solver)
- [Upstream changelog/diff](https://github.com/conda/conda-libmamba-solver/pull/492)
- https://github.com/conda/conda-libmamba-solver/pull/492
- https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/800
- libmamba recently released the first RC for the v2 series. The 2.0 final will follow at some point, and it contains API changes that will break conda-libmamba-solver. Defensively adding a pin to prevent it.
> Pin libmambapy <2

- generate_numpy2_patch.py
- numpy2_patch.json
-	Corrected the NumPy2 hotfix: Adjusted the hotfix to allow specific patches to be excluded, providing more control over which patches are applied.
-       Created the logic for hypothesis 6.111.0 to not be affected by this script
> Hypothesis hotfix exclusion

- main.py
Creating an upper bound on basemap constraint.
Currently trying to install it yields:
```
conda create --dry-run -n bm_test basemap
Channels:
- defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed
LibMambaUnsatisfiableError: Encountered problems while solving:
- package basemap-1.2.2-py38hd91d049_1 requires proj >=7.2.0,<7.2.1.0a0, but none of the providers can be installed
Could not solve for environment specs
The following packages are incompatible
└─ basemap is installable with the potential options
├─ basemap 1.2.2 would require
│  └─ proj [<6 |>=7.2.0,<7.2.1.0a0 ] with the potential options
│     ├─ proj 7.2.0, which can be installed;
│     └─ proj <6 conflicts with any installable versions previously reported;
├─ basemap 1.2.2 …
```
> Basemap uninstall fix.

- main.py
conda-libmamba-solver <= 24.7
- [{ticket_number}]() 
- [Upstream repository]()
- [Upstream changelog/diff]()
- ...
- Some conda-libmamba-solver builds were not patched for libmambapy<2. This leaves an opportunity for users mixing conda-forge and defaults to upgrade to mamba v2, which would cause conda-libmamba-solver to break.
> Pin `libmambapy<2` in all conda-libmamba-solver builds

- main.py
- [PKG-5500]
- [test-hotfix.py output](https://github.com/user-attachments/files/16554007/test-hotfix-output.txt)
- Per [this issue](https://github.com/ray-project/ray/issues/41267), `ray` depends on `async-timeout`, but has relied on `aiohttp` to provide it. Since`aiohttp` no longer requires `async-timeout`, it's necessary to add it to `ray`.
- I've confirmed that `async-timeout` has been imported since at least `ray` 1.0, and therefore applies to all versions present on main.
[PKG-5500]: https://anaconda.atlassian.net/browse/PKG-5500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add async-timeout to ray-core

- main.py
- [PKG-6113](https://anaconda.atlassian.net/browse/PKG-6113)
- Update poppler downstream deps to have an upper bound
[PKG-6113]: https://anaconda.atlassian.net/browse/PKG-6113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added fix for poppler 24.09.0

- main.py
`anaconda-cloud-auth` in `0.7.0+` introduced changes that are incompatible with previous releases. Those changes affected multiple of our products (_`anaconda-navigator` and `anaconda-toolbox` in this PR in particular_). To mitigate the issue - we are adding upper boundaries to forbid installing incompatible apps and libraries together.
_P.S. all new navigator and toolbox releases already have dependency set to the ` anaconda-cloud-auth>=0.7.1` so they should not be affected when they release_
> NAVI-279: incompatibilities with anaconda-cloud-auth

- main.py
- [PKG-6182](https://anaconda.atlassian.net/browse/PKG-6182) 
- `anaconda-cli-base 0.4.1 build number 0` doesn't have `run_constrained` to ensure that a version of `anaconda-cli-base` cannot be installed if an incompatible older version of `anaconda-client` is installed.
If you try to install `anaconda-client=1.12` with `anaconda-cloud-auth=0.7.2`:
`conda create -n dry --dry-run -c defaults --override-channels anaconda-client=1.12 anaconda-cloud-auth=0.7.2`
then **anaconda-cli-base-0.4.1-py'*'_0** will be picked up but _NOT_ **_1**. This can break many **anaconda-client** users
`run_constrained` has been added in [anaconda-cli-base 0.4.1 build number 1](https://github.com/AnacondaRecipes/anaconda-cli-base-feedstock/pull/5/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c …
> Revoke anaconda-cli-base-0.4.1 build number 0 because of missing run_constrained

- main.py
- r.py
libarchive introduced an abi breaking change (for us) in 3.7.5: https://github.com/libarchive/libarchive/pull/1976
This change protects existing affected packages.
> handle libarchive 3.7.5

- main.py
cudnn has dependencies on cuda and glibc which are currently undeclared:
- cudnn 8.9.2 is max compatible with cudatoolkit 12.1; glibc 2.19 on x86_64; glibc 2.28 on aarch64: https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-892/support-matrix/index.html
- cudnn 9.1.1 is max compatible with cudatoolkit 12.4; glibc 2.28 on x86_64; glibc 2.28 on aarch64: https://docs.nvidia.com/deeplearning/cudnn/backend/v9.1.1/reference/support-matrix.html#linux
Below is the output from `test-hotfix.py`
```
(bld) dpetry@Daniels-MacBook-Pro ~/Sandbox/distro-tools/repodata-hotfixes (dpetry/cudnn-glibc-compat) $ python test-hotfix.py main --subdirs linux-64 linux-aarch64
Creating channel directory structure for channel 'main' and platforms ['linux-64', 'linux-aarch64']
Applying url to alias main. …
```
> Apply hotfixes for cudnn compatibility

- main.py
anaconda-navigator
- [NAVI-384](https://anaconda.atlassian.net/browse/NAVI-384)
`anaconda-cloud-auth>=0.8.0` introduced changes that make it incompatible with existing releases of `anaconda-navigator`. This PR adds `anaconda-cloud-auth<0.8.0` restriction to all releases of `anaconda-navigator` where it is applicable.
[NAVI-384]: https://anaconda.atlassian.net/browse/NAVI-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NAVI-384: incompatibilities with anaconda-cloud-auth

- main.py
- Update `intel-openmp` v2025.0.0 to use proper runtime constraint on `__glibc >=2.26`
> Fix intel-openmp __glibc runtime constraint

- main.py
Need to hotfix some dependents to prevent breakage once Distro release 2025.04 comes out.
We need to add a negative dependency pin to `anaconda-cloud-auth!=0.8.2` for the components of `anaconda-toolbox`.
> anaconda-toolbox 4.1.0 -> anaconda-cloud-auth !=0.8.2

- main.py
The latest `conda-project` package is not compatible with `conda-lock` 3.0.0. See https://github.com/conda-incubator/conda-project/issues/183.
https://anaconda.atlassian.net/browse/PKG-8069
> Fix incompatibility between conda-project and conda-lock 3 (PKG-8069)

- main.py
Also add reference to issue https://github.com/anaconda/conda-anaconda-telemetry/issues/127
conda-anaconda-telemetry 0.2.0
Refs https://github.com/AnacondaRecipes/private_conda_recipes/pull/291 and [PKG-8620](https://anaconda.atlassian.net/browse/PKG-8620)
- We need to prevent older versions of conda-anaconda-telemetry from being installed with conda to fix an issue with the plugin and non-cloned channels on anaconda.org.
[PKG-8620]: https://anaconda.atlassian.net/browse/PKG-8620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update conda-anaconda-telemetry version constraint to >=0.2.0 

- main.py
[URSA-155](https://anaconda.atlassian.net/issues/URSA-155)
This PR adds a run constraint to ensure that conda packages version 24.11.0 and above require `conda-anaconda-tos>=0.2.0`.
- Added a new hotfix section in `main.py` that patches repodata for conda>=24.11.0
- The constraint ensures compatibility with the lowest possible version of conda that works with the current version of `conda-anaconda-tos`
- Follows the same pattern as the existing `conda-anaconda-telemetry` constraint for consistency
The hotfix:
1. Checks if the package name is "conda" and the version is `>= 24.11.0`
2. Filters out any existing `conda-anaconda-tos` constraints from the constraints list
3. Adds the new constraint `conda-anaconda-tos >=0.2.0`
This ensures that users installing conda 24.11.0 or later will …
> URSA-155: Install conda-anaconda-tos>=0.2.0 for conda>=24.11.0.

- main.py
conda-anaconda-tos 0.2.1
- [Upstream repository](https://github.com/anaconda/conda-anaconda-tos)
- [Upstream changelog/diff]()
- https://github.com/anaconda/conda-anaconda-tos/issues/231
- This is an urgent change to require the just released conda-anaconda-tos 0.2.1
> Require conda-anaconda-tos 0.2.1.

- main.py
constrain pytorch to corresponding libtorch variant.
At the moment, it is possible to install pytorch gpu with the cpu variant of libtorch. This can lead to crashes.
Discovered while working on https://github.com/AnacondaRecipes/llama.cpp-feedstock/pull/16
> constrain pytorch to corresponding libtorch variant

- main.py
conda-anaconda-telemetry 0.3.0
- [PKG-9286](https://anaconda.atlassian.net/browse/PKG-9286)
- [Upstream repository](https://github.com/anaconda/conda-anaconda-telemetry/)
- [Upstream changelog/diff](https://github.com/anaconda/conda-anaconda-telemetry/releases/tag/0.3.0)
- https://github.com/AnacondaRecipes/private_conda_recipes/pull/295
- Follow-up to https://github.com/AnacondaRecipes/private_conda_recipes/pull/295
[PKG-9286]: https://anaconda.atlassian.net/browse/PKG-9286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bump up constraint for conda-anaconda-telemetry to 0.3.0.

- main.py
conda-anaconda-telemetry 0.3.0-1
- [PKG-9286](https://anaconda.atlassian.net/browse/PKG-9286)
- [Upstream repository](https://github.com/anaconda/conda-anaconda-telemetry/)
- [Upstream changelog/diff](https://github.com/anaconda/conda-anaconda-telemetry/releases/tag/0.3.0)
Now that conda-anaconda-telemetry 0.3.0 is released as a noarch package via https://github.com/AnacondaRecipes/conda-anaconda-telemetry-feedstock/pull/1, we can also have osx-64 use that.
- Follow-up to:
- https://github.com/AnacondaRecipes/private_conda_recipes/pull/295
- https://github.com/AnacondaRecipes/repodata-hotfixes/pull/277
- https://github.com/AnacondaRecipes/repodata-hotfixes/pull/278
- https://github.com/AnacondaRecipes/conda-anaconda-telemetry-feedstock/pull/1
- …
> Use the new noarch release of conda-anaconda-telemetry (0.3.0-1).

- main.py
As highlighted in libtheora's release notes, the soname changed between version 1.1.1 and version 1.2.0.
Packages built against 1.1.1 must be guarded from being installed with 1.2.0.
libtheora 1.2.0 PR: https://github.com/AnacondaRecipes/libtheora-feedstock/pull/2
https://anaconda.atlassian.net/browse/PKG-9560
> hotfix for libtheora breaking change

- main.py
zlib 1.2.13-1.3.1
- [PKG-9454](https://anaconda.atlassian.net/browse/PKG-9454)
- Recipe: https://github.com/AnacondaRecipes/zlib-feedstock
- ABI report: https://github.com/AnacondaRecipes/zlib-feedstock/pull/22#issuecomment-3225826230
- zlib 1.3 was found to be ABI compatible with 1.2 while working on PR https://github.com/AnacondaRecipes/zlib-feedstock/pull/22 .
The goal is to make existing packages built against zlib 1.2 compatible with zlib 1.3 by changing the depends part.
zlib >=1.2.11,<1.3.0a0 to zlib >=1.2.11,<2.0.0a0
zlib >=1.2.12,<1.3.0a0 to zlib >=1.2.12,<2.0.0a0
zlib >=1.2.13,<1.3.0a0 to zlib >=1.2.13,<2.0.0a0
The patch will be restricted to packages on the main channel built for win-64, linux-64, linux-aarch64 and osx-arm-64.
[PKG-9454]: …
> Loosen existing zlib pins

- main.py
Remove hotfix preventing releasing nomkl for windows to allow for openblas support. 
Test results below 
[test.log](https://github.com/user-attachments/files/22547658/test.log)
> Allow nomkl on windows.

- main.py
conda 25.9.0
- [{ticket_number}]() 
- [Upstream repository]()
- [Upstream changelog/diff]()
- ...
- https://github.com/conda/conda/pull/15285
> Bump `conda 25.9.0`'s `conda-libmamba-solver` version

- main.py
conda-token <0.6.1
- [Upstream repository](https://github.com/anaconda/conda-token)
- [CLI-3](https://anaconda.atlassian.net/browse/CLI-3)
- conda-token 0.6.0 and older are not compatible with conda 25.9 and later due to the removal of a deprecated `conda.cli.python_api` module.
[CLI-3]: https://anaconda.atlassian.net/browse/CLI-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CLI-3: Add conda<25.9 bound for existing versions of conda-token
