- main.py
See https://github.com/jupyter/notebook/issues/4439
> upper bound on tornado dep for notebook <5.7.6

- main.py
See AnacondaRecipes/aggregate#126
> cudatoolkit fixes for cupy and nccl

- r.py
fixes https://github.com/conda/conda/issues/8821
fixes https://github.com/ContinuumIO/anaconda-issues/issues/11042
> fix r track_features flip hotfix causing sha256 mismatches in .conda

- main.py
> hotfix anaconda-custom to add _anaconda_depends dep

- main.py
https://github.com/conda/conda-build/issues/3643
> bump conda dep for conda-build to 4.5

- main.py
> constructor <3 needs conda <4.6

- main.py
fixes https://github.com/ContinuumIO/anaconda-issues/issues/11389
> add tbb4py dep to numpy-base mkl builds

- main.py
> add upper 4.7 bound to libnetcdf

- main.py
Copied from https://github.com/conda-forge/conda-forge-repodata-patches-feedstock
Removed a lot of hacks from conda-forge because the repodata here is much much cleaner than conda-forge.
> Add a constraint on python_abi

- main.py
Add a constrains entry on the corresponding __cuda virtual package to
the cudatoolkit packages.
closes conda/conda#9115
> add constrains entry on __cuda to cudatoolkit

- main.py
see: https://github.com/pallets/flask/pull/3497
> restrict werkzeug to <1.0 for flask < 1.0

- main.py
Fixes conda-forge/ipython-feedstock#127
> Patch ipython deps to set upper bound for jedi

- main.py
Added Python >=3.7, imagecodecs >=2021.3.31 dependency for tifffile 2021.3.31 in `main.py`.
Closes #118.
> Added Python >=3.7, imagecodecs >=2021.3.31 dependency for tifffile 2021.3.31

- main.py
Added patch to Panel < 0.11.0 requires bokeh < 2.3 in main.py
> Panel < 0.11.0 requires bokeh < 2.3

- index_versions.yml
This just adds a comment to the file index_versions.yml, explaining its purpose.
> Explain index_versions.yml in a comment in the file

- test-hotfix.py
* Make diff format and number of context lines arguments functional
* More consistent naming scheme for reference and patched repodata files
> Minor fixes to test script

- main.py
See https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/3#issuecomment-1174700925
cc @chenghlee @jezdez
> patch conda-libmamba-solver 22.6 so it requires conda 4.13+

- main.py
Resolves numpy pinning issue described in https://anaconda.atlassian.net/browse/PKG-313
> Moved linux-aarch64 numpy fix above other numpy fixes

- README.md
- main.py
scipy 1.8 and 1.9 introduce breaking API changes breaking theano and pyamg.
> add scipy<1.8 for some packages + add osx-arm64

- main.py
We need to hit 0.54.0 as well, because there are some version differences between the platforms
> one more hotfix for numba

- main.py
Same as https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/360
cc @jezdez
> pin upper bounds in conda-libmamba-solver

- main.py
See https://github.com/conda/constructor/pull/627
> pin conda <23.1 in constructor

- main.py
> Fix for a typo

- main.py
Prevents installing both MKL and OpenBLAS within a single environment, which is (arguably) undesireable behavior we're currently seeing when trying to generate the `anaconda` meta-package using the `libmamba` solver.
> Require BLAS mutex on PyTorch x86_64 (*-64) builds

- main.py
The pandas error is fixed in 3.36.0.
> [PKG-3142] Orange3 hotfix

- main.py
Fix issue with loading the JSON file
> add correct path management for numpy 2 patch

- main.py
Adding constraint to account for conda-anaconda-telemetry bugfix
Add run constraint for conda to fix plugin here:
- https://github.com/anaconda/conda-anaconda-telemetry/issues/87
- https://github.com/anaconda/conda-anaconda-telemetry/pull/96
> Added constraint for conda-anaconda-telemetry 0.1.2 
